name: MySQL
category: database
port: "${MYSQL_PORT:-3306}"
url: "localhost:${MYSQL_PORT:-3306}"

healthcheck:
  type: exec
  command:
    - mysqladmin
    - ping
    - -h
    - localhost
    - -P
    - ${MYSQL_PORT:-3306}
