name: PostgreSQL
category: database
port: "${POSTGRES_PORT:-5432}"
url: "localhost:${POSTGRES_PORT:-5432}"

healthcheck:
  type: exec
  command:
    - pg_isready
    - -U
    - ${POSTGRES_USER:-analyticsUser}
    - -d
    - ${POSTGRES_DB:-analytics}
