services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    profiles: ["kibana"]
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - ecosystem
